// 英文版天体文字（类型、简介、参数）与漫游字幕；中文原文在 data.js
export const BODIES_EN = {
  sun: { type: 'Star · G2V yellow dwarf', desc: 'The heart of the Solar System, holding 99.86% of its mass. Its core reaches about 15.7 million K, and every second it turns some 4 million tonnes of matter into energy.',
    stats: [['Radius', '696,340 km'], ['Mass', '1.989 × 10³⁰ kg'], ['Surface temp.', '5,772 K'], ['Rotation', '25.4 days (equator)'], ['Age', '≈ 4.6 billion years']] },
  mercury: { type: 'Terrestrial planet', desc: 'The smallest planet and the closest to the Sun. With no atmosphere to hold heat, its day–night temperature swing exceeds 600 °C, and craters cover its surface.',
    stats: [['Radius', '2,439.7 km'], ['Mass', '3.301 × 10²³ kg'], ['Orbital period', '87.97 days'], ['Rotation', '58.65 days'], ['Axial tilt', '0.03°'], ['Surface temp.', '−173 to 427 °C'], ['Moons', '0']] },
  venus: { type: 'Terrestrial planet', desc: 'A thick carbon-dioxide atmosphere drives a runaway greenhouse effect, making it the hottest planet in the Solar System. It spins the opposite way to most planets.',
    stats: [['Radius', '6,051.8 km'], ['Mass', '4.867 × 10²⁴ kg'], ['Orbital period', '224.70 days'], ['Rotation', '243.02 days (retrograde)'], ['Axial tilt', '177.4°'], ['Surface temp.', '464 °C'], ['Moons', '0']] },
  earth: { type: 'Terrestrial planet · Home', desc: 'The only world known to harbour life. Oceans cover 71% of its surface, and its atmosphere and magnetic field together shield the biosphere.',
    stats: [['Radius', '6,371.0 km'], ['Mass', '5.972 × 10²⁴ kg'], ['Orbital period', '365.256 days'], ['Rotation', '23 h 56 min'], ['Axial tilt', '23.44°'], ['Mean temp.', '15 °C'], ['Moons', '1']] },
  moon: { type: "Earth's natural satellite", desc: "Earth's only natural satellite. Tidal locking keeps the same face turned towards us; the dark “seas” (maria) on the near side are ancient lava plains.",
    stats: [['Radius', '1,737.4 km'], ['Mass', '7.342 × 10²² kg'], ['Orbital period', '27.32 days'], ['Rotation', '27.32 days (synchronous)'], ['Mean distance', '384,400 km'], ['Surface temp.', '−173 to 127 °C']] },
  mars: { type: 'Terrestrial planet', desc: 'Its red colour comes from iron oxide on the surface. It hosts the tallest volcano in the Solar System, Olympus Mons, and the 4,000 km-long Valles Marineris canyon.',
    stats: [['Radius', '3,389.5 km'], ['Mass', '6.417 × 10²³ kg'], ['Orbital period', '686.98 days'], ['Rotation', '24 h 37 min'], ['Axial tilt', '25.19°'], ['Mean temp.', '−63 °C'], ['Moons', '2']] },
  phobos: { type: 'Moon of Mars', desc: 'Only 6,000 km above the Martian surface, it rises in the west and sets in the east as seen from Mars. Tides are dragging it inward; in about 50 million years it will break up into a ring.',
    stats: [['Size', '27 × 22 × 18 km'], ['Orbital period', '7 h 39 min'], ['Orbital radius', '9,376 km'], ['Largest crater', 'Stickney (9 km)']] },
  deimos: { type: 'Moon of Mars', desc: "The smaller and more distant of Mars' two moons. A thick blanket of regolith makes its surface look smooth; it may be a captured asteroid.",
    stats: [['Size', '15 × 12 × 11 km'], ['Orbital period', '30 h 18 min'], ['Orbital radius', '23,463 km']] },
  jupiter: { type: 'Gas giant', desc: 'The largest planet, 2.5 times as massive as all the others combined. The Great Red Spot is a storm bigger than Earth that has raged for centuries.',
    stats: [['Radius', '69,911 km'], ['Mass', '1.898 × 10²⁷ kg'], ['Orbital period', '11.86 years'], ['Rotation', '9 h 56 min'], ['Axial tilt', '3.13°'], ['Cloud-top temp.', '−110 °C'], ['Moons', '95+']] },
  io: { type: 'Galilean moon', desc: 'The most volcanically active body in the Solar System. Tidal heating from Jupiter powers more than 400 active volcanoes, and sulphur coats its surface.',
    stats: [['Radius', '1,821.6 km'], ['Mass', '8.932 × 10²² kg'], ['Orbital period', '1.769 days'], ['Rotation', 'Synchronous']] },
  europa: { type: 'Galilean moon', desc: 'Beneath its ice shell may lie a global ocean of liquid water, making it a prime target in the search for life beyond Earth.',
    stats: [['Radius', '1,560.8 km'], ['Mass', '4.800 × 10²² kg'], ['Orbital period', '3.551 days'], ['Rotation', 'Synchronous']] },
  ganymede: { type: 'Galilean moon', desc: 'The largest moon in the Solar System—bigger than Mercury—and the only moon known to generate its own magnetic field.',
    stats: [['Radius', '2,634.1 km'], ['Mass', '1.482 × 10²³ kg'], ['Orbital period', '7.155 days'], ['Rotation', 'Synchronous']] },
  callisto: { type: 'Galilean moon', desc: 'One of the most heavily cratered bodies in the Solar System; its ancient surface has barely been touched by geological activity.',
    stats: [['Radius', '2,410.3 km'], ['Mass', '1.076 × 10²³ kg'], ['Orbital period', '16.689 days'], ['Rotation', 'Synchronous']] },
  saturn: { type: 'Gas giant', desc: 'Famous for its magnificent rings, made mostly of ice and spanning about 280,000 km yet usually less than 1 km thick. Its mean density is lower than water.',
    stats: [['Radius', '58,232 km'], ['Mass', '5.683 × 10²⁶ kg'], ['Orbital period', '29.46 years'], ['Rotation', '10 h 33 min'], ['Axial tilt', '26.73°'], ['Cloud-top temp.', '−140 °C'], ['Moons', '274+']] },
  mimas: { type: 'Moon of Saturn', desc: "The giant Herschel crater, 139 km across—about a third of the moon's own diameter—makes it look like the Death Star from Star Wars.",
    stats: [['Radius', '198.2 km'], ['Orbital period', '22 h 37 min'], ['Orbital radius', '185,539 km']] },
  enceladus: { type: 'Moon of Saturn', desc: 'One of the most reflective bodies in the Solar System. “Tiger stripe” fractures at its south pole vent plumes of water ice from a global ocean beneath the crust.',
    stats: [['Radius', '252.1 km'], ['Orbital period', '1.37 days'], ['Albedo', '0.81'], ['Subsurface ocean', 'Confirmed']] },
  tethys: { type: 'Moon of Saturn', desc: 'Made almost entirely of water ice. Ithaca Chasma, 100 km wide and 2,000 km long, wraps three-quarters of the way around the moon.',
    stats: [['Radius', '531.1 km'], ['Orbital period', '1.89 days'], ['Orbital radius', '294,619 km']] },
  dione: { type: 'Moon of Saturn', desc: 'Bright wispy lines streak its trailing hemisphere. Once mistaken for frost, they turned out—when Cassini looked closely—to be ice cliffs hundreds of metres high.',
    stats: [['Radius', '561.4 km'], ['Orbital period', '2.74 days'], ['Orbital radius', '377,396 km']] },
  rhea: { type: 'Moon of Saturn', desc: "Saturn's second-largest moon. Its ancient, heavily cratered surface is wrapped in a tenuous exosphere of oxygen and carbon dioxide.",
    stats: [['Radius', '763.8 km'], ['Orbital period', '4.52 days'], ['Orbital radius', '527,108 km']] },
  titan: { type: "Saturn's largest moon", desc: 'The only moon with a thick atmosphere. Beneath its orange haze lie lakes and rivers of liquid methane and ethane.',
    stats: [['Radius', '2,574.7 km'], ['Mass', '1.345 × 10²³ kg'], ['Orbital period', '15.945 days'], ['Surface temp.', '−179 °C'], ['Surface pressure', '1.5 atm']] },
  iapetus: { type: 'Moon of Saturn', desc: 'Its leading hemisphere is black as coal and its trailing hemisphere white as snow, while a ridge up to 20 km high runs along its equator like the seam of a walnut.',
    stats: [['Radius', '734.5 km'], ['Orbital period', '79.3 days'], ['Inclination', "15.5° (to Saturn's equator)"]] },
  uranus: { type: 'Ice giant', desc: 'Its spin axis lies almost in its orbital plane, so each pole gets 42 years of continuous daylight followed by 42 years of night.',
    stats: [['Radius', '25,362 km'], ['Mass', '8.681 × 10²⁵ kg'], ['Orbital period', '84.01 years'], ['Rotation', '17 h 14 min (retrograde)'], ['Axial tilt', '97.77°'], ['Cloud-top temp.', '−195 °C'], ['Moons', '28+']] },
  miranda: { type: 'Moon of Uranus', desc: 'A patchwork world of huge “coronae” and Verona Rupes, a cliff up to 20 km high—the tallest known in the Solar System.',
    stats: [['Radius', '235.8 km'], ['Orbital period', '1.41 days'], ['Tallest cliff', '≈ 20 km']] },
  ariel: { type: 'Moon of Uranus', desc: "The brightest of Uranus' moons, criss-crossed by huge fault valleys floored with younger, smoother material.",
    stats: [['Radius', '578.9 km'], ['Orbital period', '2.52 days'], ['Orbital radius', '191,020 km']] },
  umbriel: { type: 'Moon of Uranus', desc: "The darkest of Uranus' large moons: ancient and heavily cratered, broken only by a bright ring on the rim of Wunda crater near the equator.",
    stats: [['Radius', '584.7 km'], ['Orbital period', '4.14 days'], ['Orbital radius', '266,300 km']] },
  titania: { type: 'Moon of Uranus', desc: "Uranus' largest moon. Its enormous canyon systems may have cracked open as its interior froze and expanded.",
    stats: [['Radius', '788.9 km'], ['Orbital period', '8.71 days'], ['Orbital radius', '435,910 km']] },
  oberon: { type: 'Moon of Uranus', desc: "The outermost of Uranus' large moons: old, dim and cratered, with mysterious dark material pooled on some crater floors.",
    stats: [['Radius', '761.4 km'], ['Orbital period', '13.46 days'], ['Orbital radius', '583,520 km']] },
  neptune: { type: 'Ice giant', desc: 'The planet farthest from the Sun, home to the fiercest winds in the Solar System—up to 2,100 km/h.',
    stats: [['Radius', '24,622 km'], ['Mass', '1.024 × 10²⁶ kg'], ['Orbital period', '164.8 years'], ['Rotation', '16 h 6 min'], ['Axial tilt', '28.32°'], ['Cloud-top temp.', '−200 °C'], ['Moons', '16']] },
  triton: { type: 'Moon of Neptune', desc: 'The only large moon on a retrograde orbit, probably a captured Kuiper Belt object. Nitrogen geysers streak its southern polar cap with dark plumes.',
    stats: [['Radius', '1,353.4 km'], ['Orbital period', '5.88 days (retrograde)'], ['Surface temp.', '−235 °C'], ['Orbital radius', '354,759 km']] },
  ceres: { type: 'Dwarf planet · Asteroid Belt', desc: 'The largest object in the asteroid belt and its only dwarf planet. Dawn found bright salt deposits in Occator crater, hinting at brine below the surface.',
    stats: [['Radius', '469.7 km'], ['Mass', '9.39 × 10²⁰ kg'], ['Orbital period', '4.60 years'], ['Rotation', '9 h 4 min'], ['Surface temp.', '−105 °C']] },
  pluto: { type: 'Dwarf planet · Kuiper Belt', desc: 'Reclassified as a dwarf planet in 2006. New Horizons revealed its heart-shaped Tombaugh Regio—a young plain of nitrogen ice that keeps churning and renewing itself.',
    stats: [['Radius', '1,188.3 km'], ['Mass', '1.303 × 10²² kg'], ['Orbital period', '248 years'], ['Rotation', '6.39 days (retrograde)'], ['Axial tilt', '122.5°'], ['Surface temp.', '−230 °C'], ['Moons', '5']] },
  charon: { type: 'Moon of Pluto', desc: "Half Pluto's diameter. The two are tidally locked to each other, always showing the same face; a reddish-brown patch, Mordor Macula, caps its north pole.",
    stats: [['Radius', '606 km'], ['Orbital period', '6.39 days'], ['Orbital radius', '19,591 km']] },
  halley: { type: 'Periodic comet · 1P', desc: 'The most famous periodic comet, returning about every 76 years on a retrograde orbit. It last came by in 1986 and next reaches perihelion in July 2061—set the clock to then to see its tail.',
    stats: [['Nucleus', '15 × 8 km'], ['Orbital period', '≈ 76 years'], ['Perihelion', '0.57 AU'], ['Aphelion', '35 AU'], ['Next perihelion', 'Jul 2061']] },
  encke: { type: 'Periodic comet · 2P', desc: 'One of the shortest-period comets known, circling the Sun every 3.3 years. Near the Sun its ices sublimate into a coma and two tails: a blue ion tail pointing straight away from the Sun and a yellow-white dust tail curving along the orbit.',
    stats: [['Nucleus radius', '≈ 2.4 km'], ['Orbital period', '3.30 years'], ['Perihelion', '0.34 AU'], ['Aphelion', '4.10 AU'], ['Next perihelion', 'Feb 2027']] },
  halebopp: { type: 'Long-period comet · C/1995 O1', desc: 'The “Great Comet” of 1997, visible to the naked eye for 18 months. Its nucleus, about 60 km across, is one of the largest ever recorded; it will not return for about 2,400 years.',
    stats: [['Nucleus diameter', '≈ 60 km'], ['Orbital period', '≈ 2,400 years'], ['Perihelion', '0.89 AU'], ['Last perihelion', 'Apr 1997']] },
  swifttuttle: { type: 'Periodic comet · 109P', desc: 'Parent of the Perseid meteor shower: every August Earth ploughs through the dust it left behind. It orbits every 133 years and returns in 2126.',
    stats: [['Nucleus diameter', '≈ 26 km'], ['Orbital period', '133 years'], ['Perihelion', '0.96 AU'], ['Meteor shower', 'Perseids (August)']] },
  tempeltuttle: { type: 'Periodic comet · 55P', desc: 'Parent of the Leonid meteor shower, orbiting the Sun backwards every 33 years. In 1833 and 1966 it produced meteor storms of tens of thousands per hour.',
    stats: [['Nucleus diameter', '≈ 3.6 km'], ['Orbital period', '33.2 years'], ['Perihelion', '0.98 AU'], ['Meteor shower', 'Leonids (November)']] },
  churyumov: { type: 'Periodic comet · 67P', desc: 'Orbited by Rosetta for two years and the first comet ever landed on, by Philae. Its two-lobed nucleus is shaped like a rubber duck.',
    stats: [['Nucleus', '4.1 × 3.3 km'], ['Orbital period', '6.44 years'], ['Perihelion', '1.24 AU'], ['Spacecraft', 'Rosetta (2014–2016)']] },
  ponsbrooks: { type: 'Periodic comet · 12P', desc: 'A Halley-type comet with a 71-year period. During its 2024 return it erupted repeatedly, its coma briefly taking on the shape of “devil horns”.',
    stats: [['Nucleus diameter', '≈ 30 km'], ['Orbital period', '71 years'], ['Perihelion', '0.78 AU'], ['Last perihelion', 'Apr 2024']] },
  system: { type: 'Planetary system · Orion Arm', desc: 'Born about 4.6 billion years ago from a collapsing molecular cloud. Eight planets circle the Sun in the same direction on nearly the same plane; beyond them lie the Kuiper Belt and the distant Oort Cloud.',
    stats: [['Age', '≈ 4.6 billion years'], ['Planets', '8'], ['Dwarf planets', '5 recognised'], ['Planetary moons', '400+'], ["Sun's share of mass", '99.86%'], ['Heliopause', '≈ 120 AU'], ['Galactic orbit', '≈ 230 million years']] },
};

// 漫游字幕（按 TOUR 的站点 id）
export const TOUR_EN = {
  sun: 'Sunlight takes 8 minutes 20 seconds to reach Earth.',
  mercury: 'From one sunrise to the next on Mercury takes about 176 Earth days—longer than its year.',
  venus: "The pressure at Venus' surface is 92 times Earth's, and it is hot enough to melt lead.",
  earth: "From space, Earth's night side glitters with billions of lights.",
  moon: 'The Moon is drifting away from Earth by about 3.8 cm a year.',
  mars: 'Olympus Mons rises about 22 km—two and a half times the height of Everest.',
  ceres: "Ceres holds about a third of the asteroid belt's total mass.",
  jupiter: "Jupiter's Great Red Spot has raged for at least 350 years, with winds up to 430 km/h.",
  io: "Io's volcanoes hurl material up to 400 km into space.",
  europa: "Europa's hidden ocean may hold twice as much water as all of Earth's oceans.",
  saturn: "Saturn's rings, backlit by the Sun—about 280,000 km wide, yet often less than 1 km thick.",
  enceladus: "The icy plumes from Enceladus' south pole feed Saturn's E ring.",
  titan: 'Apart from Earth, Titan is the only world with stable liquid on its surface: lakes of liquid methane.',
  uranus: 'Uranus rolls around the Sun on its side; each pole gets 42 years of daylight, then 42 years of night.',
  neptune: 'Winds on Neptune reach 2,100 km/h—the fiercest in the Solar System.',
  triton: 'Triton is slowly spiralling inward on its retrograde orbit and will one day be torn into a ring by Neptune.',
  pluto: "Pluto's “heart” is a plain of nitrogen ice that keeps overturning; beside it is its largest moon, Charon.",
  overview: 'One star, eight planets, hundreds of moons and countless smaller worlds.',
};
